### PR TITLE
add setFieldError and setError functions to the useField hook

### PR DESCRIPTION
**Pull request by JonathanCa97**
I have a use case where I have to set an error to a field if a specific field his value changes.

### CODE REVIEW

**Comment by JonathanCa97** [comment]
Shit, do you have a .prettierrc file @JoviDeCroock  :P ?

**Comment by JoviDeCroock** [comment]
Hmm, this feels very imperative since I was actually contemplating on removing `setFieldValue` all together from `useField` this in favor of a new hook called `useSpy` where we can observe a certain value and trigger a callback from it.

Linearly we could do this here I think, how does this not fit in the case of `validate`?

**Comment by JonathanCa97** [comment]
I have the following case. I have an object called 'Dialogstate', which has a name and a very nested config.
So I have a form where the user has to give a name to the Dialogstate, and has to configure the config.
In those configs, there are dropdowns (called nextDialogstate) which can also point to a Dialogstate. But this is a creatable dropdown. So it's not only possible to point to a new dialogstate, but fill in a new name. The back end will create those new dialogstates later.

If I use the code I added in this PR. I can do smth like this:
```js
const [_, {value: currentDialogstateName}] = useField<string>('name')
const [{setError}] = useField<string>('very.very.very.nested.nextDialogstateId')

const onSelectInputChange = ({id, name}: {id?: string, name: string}) => {
        if(!id && name === currentDialogstateName) setError('you can't have the same name as the current diaogstate name)
        //....
}
```

If I do this with a validate, my code can get nasty because this config can be pretty big

**Comment by JoviDeCroock** [comment]
So for your use case `useSpy` would be perfect. Would you be okay with using `useFormConnect` for now or? I assume you will need this in 3.2.0 instead of the current target of your PR which is 4.0.0

**Comment by JonathanCa97** [comment]
Indeed, you're right!

**Comment by JoviDeCroock** [comment]
If you are okay with using `useFormConnect` I'll make sure to publish 3.2.0 tonight, if you're not just supply some arguments and I'll consider them when preparing the release.

Big thanks for taking time out of your day to PR already

**Comment by Pruxis** [comment]
Any reason why opting for another hook instead of options on the useField hook itself, passing spies? Is it for memoization or?

**Comment by JoviDeCroock** [comment]
@Pruxis I think it enforces a paradigm that is very light on bundle size and is semantically a lot easier to read let's compare both examples

```
MyNameComponent.js

const [_, {value: currentDialogstateName}] = useField<string>('name') // the real field
const [{setError}] = useField<string>('very.very.very.nested.nextDialogstateId') // Irrelevant field

onChange(() => do smth with both the above)
```

Now with useSpy

```
MyNameComponent.js

const [_, {value: currentDialogstateName}] = useField<string>('name') // the real field
onChange(() => only changename)

MyNestedField.js
useSpy('name', (newValue, { setError }) => do smth) 
```

**Pull request closed without merging**
