### PR TITLE
Form shouldn't validate on first render (mount)

### PR DESCRIPTION
**Pull request by JonathanCa97**
This is a quick fix if no validateOnBlur and no validateOnChange. Can be fixed cleaner maybe later

### CODE REVIEW

**Comment by JoviDeCroock** [comment]
This will probably be a tad smaller since `return` is a keyword and by extension does not compress/mangle well

```
      React.useEffect(() => {
        if (validateOnBlur || validateOnChange) {
          validateForm();
        }
      }, [validateOnBlur && touched, validateOnChange && values]);
```

**Comment by JonathanCa97** [comment]
okay, good for me :D

**Comment by JoviDeCroock** [comment]
@all-contributors add @JonathanCa97 for bug

**Comment by JoviDeCroock** [comment]
@JonathanCa97 your fix is published in 3.1.1 and the fix will be in 4 after I merge in #65

**Comment by JonathanCa97** [comment]
Okay perfect, thanks for the quick response!!

**Pull request merged**
