### PR TITLE
chore: reducing duplicate if into single statement

### PR DESCRIPTION
**Pull request by Pruxis**
As I was reading through the code I noticed this, a minor improvement.

### CODE REVIEW

**Comment by Pruxis** [comment]
I noticed that this is done on a lot of components, I'll add the rest to this pull request when I find more time.

**Comment by JoviDeCroock** [comment]
Some uglifiers don't remove this code in production if you don't make it a __dev__ check, so when adding the && `!component` it could be left untouched. I'll test this when I can.

Note that this was last time I checked.

**Comment by JoviDeCroock** [comment]
@all-contributors please add @Pruxisfor for code

**Comment by JoviDeCroock** [comment]
@all-contributors please add @Pruxis for for code

**Comment by Pruxis** [comment]
Hmhm, I haven't tested this on older uglifiers but have never had issues with Terser & babel-uglify that's default in CRA at this point. I don't have a lot of free time to test this thoroughly tho

**Comment by JoviDeCroock** [comment]
No worries, I'll take the testing on me. Just saying but avoid using babel-minify this can cause some nasty performance downgrades in React.

**Comment by JoviDeCroock** [comment]
Thanks for helping out with this, I've implemented it myself but credits still go to you for noticing it! Thanks again for the wonderfull PR's

**Pull request closed without merging**
